spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8081'

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8081'
